name: Validation test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, dev, develop, master]
  workflow_call:
  merge_group:

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:

  Test-Job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test step
        run: |
          echo "Completed"
